general:
    use_proxy: yes
    # NOTSET=0, DEBUG=10, INFO=20, WARNING=30, ERROR=40
    log_level: 20
    #proxy authentication type - basic, digest
    proxy_auth_type: digest

proxy:
    host: 192.168.1.2
    port: 3128
    user: xxxx
    password: xxxx
    # timeout period in sec - default 60
    timeout: 60 

https_servers:
    - google.com
    # - protonmail.com

elastic:
    host: localhost
    port: 9200
    index: ssllabs_api
    doc_type: https_settings
